sqslog:
  queue: JDDLogQueue.fifo
  aws_key_id: <your AWS SQS key id>
  secret_key: <your AWS SQS secret key>
  aws_region: us-xxxx-N
loglevel: DEBUG
logfile: jdd-log.txt
job_queries:
- job_name: Software Engineer
- job_name: Backend Developer
job_services:
- Authorization-Key: YourAPIKey
  User-Agent: your@email.address
  class_name: MuseDataGrabber
  method: GET
  name: The Muse
  params:
  - category:
    - Software Engineer
    - Data Science
    - IT
    level:
    - Senior Level
    - Mid Level
    location: United States
  url: https://www.themuse.com/api/public/jobs
mongodb:
- connection: mongodb+srv://<user>:<password>@cluster0.abcd.mongodb.net/<default_database>?retryWrites=true&w=majority
