job_queries:
- job_name: Software Engineer
- job_name: Backend Developer
job_services:
- Authorization-Key: YourAPIKey
  User-Agent: your@email.address
  class_name: MuseDataGrabber
  method: GET
  name: The Muse
  params:
  - category:
    - Software Engineer
    - Data Science
    - IT
    level:
    - Senior Level
    - Mid Level
    location: United States
  url: https://www.themuse.com/api/public/jobs
