job_queries:
- job_name: Software Engineer
- job_name: Backend Developer
job_services:
- class_name: jspgrabber.MuseDataGrabber
  Authorization-Key: YourAPIKey
  User-Agent: your@email.address
  method: GET
  name: The Muse
  url: https://www.themuse.com/api/public/jobs
  params:
    - category: Data Science
      category: IT
      category: Software Engineer
      level: Mid Level
      level: Senior Level
      location: United States
